# DISCORD
BOT_VERSION = "4.0.0"
BOT_PREFIX = "."

# REDDIT
SUBREDDIT = "xyitest"
REMOVED_FLAIR_CONTAINS = "removed:"

# SQL
POINT_LIMIT = 10 # BAN USER IF THEY HAVE MORE OR EQUAL TO POINT LIMIT

# BANS
BAN_LENGTH = 7 # LENGTH OF A BAN IN DAYS
BAN_REASON = ""
BAN_MESSAGE = ""
BAN_NOTE = ""